### ISSUE TITLE
Mangles characters in code block

### ISSUE THREAD

**Issue by rmoff** [RittmanMead/md_to_conf#1]
`<` because `&lt;` etc

**Comment by PMudra** [comment]
This README.md will produce an error:

### Markdown input
````markdown
# Hello world

```html
<img src="hello.world.png" />
```
````
### Error
```
Updating page...
Traceback (most recent call last):
  File "md2conf.py", line 456, in <module>
    main()
  File "md2conf.py", line 451, in main
    createPage(title, html, ancestors)
  File "md2conf.py", line 285, in createPage
    updatePage(pageId, title, body, version, ancestors, attachments)
  File "md2conf.py", line 315, in updatePage
    body = addImages(pageId, body)
  File "md2conf.py", line 219, in addImages
    altText = re.search('alt="(.*?)"', tag).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
